run:
  timeout: 1m

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asciicheck
    - bodyclose
    - cyclop
    - decorder
    # - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    # - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - importas
    - interfacebloat
    - lll
    - makezero
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - stylecheck
    - sqlclosecheck
    - tagliatelle
    - tenv
    # - testpackage
    # - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl

issues:
  exclude-rules:
    - path: (_test\.go|tests)
      linters:
        - bodyclose
        - dupl
        - funlen
        - gochecknoglobals
        - goerr113
        - gosec
        - noctx
    - path: (internal/handler/http)
      linters:
        - godot

linters-settings:
  # depguard:
  #   rules:
  #     main:
  #       files:
  #         - $all
  #         - "!$test"
  #       allow:
  #         - $gostd
  #         - github.com/jackc/pgx/v5
  #         - github.com/swaggo/gin-swagger
  #         - github.com/swaggo/files
  #         - github.com/gin-gonic/gin
  #         - github.com/spf13/viper
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
        yaml: snake
        xml: snake