version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=service

  api:
    image: b0shka/backend:latest
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - GIN_MODE=release
    env_file:
      - .env
    entrypoint: [
      "/app/wait-for.sh", 
      "postgres:5432", 
      "--"
    ]
    command: ["/app/main"]
