// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	domain "github.com/b0shka/backend/internal/domain"
	gomock "github.com/golang/mock/gomock"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockUsers is a mock of Users interface.
type MockUsers struct {
	ctrl     *gomock.Controller
	recorder *MockUsersMockRecorder
}

// MockUsersMockRecorder is the mock recorder for MockUsers.
type MockUsersMockRecorder struct {
	mock *MockUsers
}

// NewMockUsers creates a new mock instance.
func NewMockUsers(ctrl *gomock.Controller) *MockUsers {
	mock := &MockUsers{ctrl: ctrl}
	mock.recorder = &MockUsersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsers) EXPECT() *MockUsersMockRecorder {
	return m.recorder
}

// AddVerifyEmail mocks base method.
func (m *MockUsers) AddVerifyEmail(ctx context.Context, verifyEmail domain.VerifyEmail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddVerifyEmail", ctx, verifyEmail)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddVerifyEmail indicates an expected call of AddVerifyEmail.
func (mr *MockUsersMockRecorder) AddVerifyEmail(ctx, verifyEmail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddVerifyEmail", reflect.TypeOf((*MockUsers)(nil).AddVerifyEmail), ctx, verifyEmail)
}

// Create mocks base method.
func (m *MockUsers) Create(ctx context.Context, user domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUsersMockRecorder) Create(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUsers)(nil).Create), ctx, user)
}

// Get mocks base method.
func (m *MockUsers) Get(ctx context.Context, identifier interface{}) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, identifier)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUsersMockRecorder) Get(ctx, identifier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUsers)(nil).Get), ctx, identifier)
}

// GetVerifyEmail mocks base method.
func (m *MockUsers) GetVerifyEmail(ctx context.Context, email, code string) (domain.VerifyEmail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVerifyEmail", ctx, email, code)
	ret0, _ := ret[0].(domain.VerifyEmail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVerifyEmail indicates an expected call of GetVerifyEmail.
func (mr *MockUsersMockRecorder) GetVerifyEmail(ctx, email, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVerifyEmail", reflect.TypeOf((*MockUsers)(nil).GetVerifyEmail), ctx, email, code)
}

// RemoveVerifyEmail mocks base method.
func (m *MockUsers) RemoveVerifyEmail(ctx context.Context, id primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveVerifyEmail", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveVerifyEmail indicates an expected call of RemoveVerifyEmail.
func (mr *MockUsersMockRecorder) RemoveVerifyEmail(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveVerifyEmail", reflect.TypeOf((*MockUsers)(nil).RemoveVerifyEmail), ctx, id)
}

// Update mocks base method.
func (m *MockUsers) Update(ctx context.Context, id primitive.ObjectID, user domain.UserUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUsersMockRecorder) Update(ctx, id, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUsers)(nil).Update), ctx, id, user)
}
