// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package repository

import (
	"database/sql"
	"time"
)

type Session struct {
	ID           string    `json:"id"`
	UserID       string    `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
}

type User struct {
	ID        string         `json:"id"`
	Email     string         `json:"email"`
	Username  sql.NullString `json:"username"`
	Photo     sql.NullString `json:"photo"`
	CreatedAt time.Time      `json:"created_at"`
}

type VerifyEmail struct {
	ID         string    `json:"id"`
	Email      string    `json:"email"`
	SecretCode string    `json:"secret_code"`
	ExpiresAt  time.Time `json:"expires_at"`
}
