version: '3.9'

services:
  api:
    image: cr.selcloud.ru/service/backend:latest
    container_name: backend
    restart: always
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    ports:
      - 8080:8080
    environment:
      - POSTGRESQL_URL
      - MIGRATION_URL
      - REDIS_ADDRESS
      - EMAIL_SERVICE_NAME
      - EMAIL_SERVICE_ADDRESS
      - EMAIL_SERVICE_PASSWORD
      - SECRET_KEY
      - CODE_SALT
      - ENV
      - HTTP_HOST

  nginx:
    image: cr.selcloud.ru/service/nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./certs/:/etc/nginx/certs/
    ports:
      - 80:80
      - 443:443
    # environment:
    #   - API_HOST=api
    #   - API_PORT=8080
    #   - SERVER_NAME=${SERVER_NAME}
    depends_on:
      - api