basePath: /api/v1/
definitions:
  http.GetUserResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
    required:
    - created_at
    - email
    - id
    type: object
  http.RefreshTokenRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  http.RefreshTokenResponse:
    properties:
      access_token:
        type: string
    type: object
  http.SendCodeRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  http.SignInRequest:
    properties:
      email:
        type: string
      secret_code:
        type: string
    required:
    - email
    - secret_code
    type: object
  http.SignInResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      session_id:
        type: string
    type: object
  http.response:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST API for Service App
  title: Service API
  version: "1.0"
paths:
  /users/:
    delete:
      consumes:
      - application/json
      description: delete user account
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/http.response'
      security:
      - UsersAuth: []
      summary: Delete User
      tags:
      - account
    get:
      consumes:
      - application/json
      description: get information account
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.GetUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/http.response'
      security:
      - UsersAuth: []
      summary: Get User
      tags:
      - account
  /users/auth/refresh:
    post:
      consumes:
      - application/json
      description: user refresh token
      parameters:
      - description: refresh info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/http.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.RefreshTokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/http.response'
      summary: User Refresh Token
      tags:
      - auth
  /users/auth/send-code:
    post:
      consumes:
      - application/json
      description: send secret code to email user
      parameters:
      - description: auth info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/http.SendCodeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/http.response'
      summary: User Send Code Email
      tags:
      - auth
  /users/auth/sign-in:
    post:
      consumes:
      - application/json
      description: user sign in
      parameters:
      - description: sign in info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/http.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.SignInResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/http.response'
      summary: User SignIn
      tags:
      - auth
securityDefinitions:
  UsersAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
