name: Release

on:
  push:
    branches:
      - main

env:
  REGISTRY: "cr.selcloud.ru/service"
  API_IMAGE: "backend"
  TAG: "latest"

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: qwerty
          POSTGRES_DB: service
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/migrate
          which migrate

      - name: Run migrations
        run: make migrateup

      - name: Test project
        run: make test

  build_and_push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build API image
        run: docker build -f Dockerfile -t $(echo $REGISTRY)/$(echo $API_IMAGE):$(echo $TAG) .

      - name: Login to Selectel Container Registry
        uses: docker/login-action@v2
        with:
          registry: cr.selcloud.ru
          username: ${{ secrets.SELECTEL_TOKEN_NAME }}
          password: ${{ secrets.SELECTEL_TOKEN_PASSWORD }}

      - name: Push API image to Docker Hub
        run: docker push $(echo $REGISTRY)/$(echo $API_IMAGE):$(echo $TAG)
      
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build_and_push
    
  #   steps:
  #     - name: Deploy to server
  #       uses: appleboy/ssh-action@v0.1.8
  #       with:
